#!/bin/sh

dnsmasq --interface=eth0 \
    --no-hosts --no-resolv \
    --dhcp-range=192.168.242.2,192.168.242.254,255.255.255.0,8h \
    --dhcp-boot=pxelinux.0,pxeserver,192.168.242.1 \
    --pxe-service=x86PC,"Install Linux",pxelinux \
    --enable-tftp --tftp-root=/tftp/ --no-daemon

# Let's be honest: I don't know if the --pxe-sefrvice option is necessary.
# The iPXE loader in QEMU boots without it.  But I know how some PXE ROMs
# can be picky, so I decided to leave it, since it shouldn't hurt.
