#!/bin/sh
# eth1 is the default created by pipework
dnsmasq \
  --interface=eth1 \
  --no-resolv \
  --dhcp-range=192.168.17.11,192.168.17.254,255.255.255.0,8h \
  --dhcp-boot=pxelinux.0,pxeserver,192.168.17.10 \
  --pxe-service=x86PC,"Install Linux",pxelinux \
  --enable-tftp --tftp-root=/tftp/ --no-daemon

