#!/bin/sh
# eth1 is the default created by pipework
pipework --wait

#dnsmasq -u lxc-dnsmasq --strict-order --bind-interfaces --pid-file=/run/lxc/dnsmasq.pid --conf-file= --listen-address 10.0.3.1 --dhcp-range 10.0.3.2,10.0.3.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --interface=lxcbr0 --dhcp-leasefile=/var/lib/misc/dnsmasq.lxcbr0.leases --dhcp-authoritative

dnsmasq \
  --interface=eth1 \
  --no-resolv \
  --dhcp-range=192.168.17.11,192.168.17.254,255.255.255.0,8h \
  --dhcp-boot=pxelinux.0,pxeserver,192.168.17.10 \
  --pxe-service=x86PC,"Install Linux",pxelinux \
  --enable-tftp --tftp-root=/tftp/ --no-daemon

